name: Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: python-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 1

      - uses: ./.github/actions/python-test
        with:
          working-directory: orthanc

      - name: Upload artifact (main push only)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v7
        with:
          name: test-py-${{ github.sha }}
          path: orthanc/outputs/
          retention-days: 90
